services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-trazoliva}
      POSTGRES_USER: ${POSTGRES_USER:-trazo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-trazo}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        COMMIT_SHA: ${COMMIT_SHA-}
        BUILD_TIME: ${BUILD_TIME-}
    restart: unless-stopped
    ports:
      # Bind to loopback by default; adjust via BACKEND_PORT
      - "${BACKEND_HOST_BIND:-127.0.0.1}:${BACKEND_PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      # Connect to db service
      DATABASE_URL: postgres://${POSTGRES_USER:-trazo}:${POSTGRES_PASSWORD:-trazo}@db:5432/${POSTGRES_DB:-trazoliva}
      # Seed admin credentials (optional)
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASS: ${ADMIN_PASS:-admin}
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Keep empty to rely on nginx proxy /api
        VITE_API_URL: ${VITE_API_URL-}
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-80}:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  pgdata:
